# Generated by Django 4.2.7 on 2023-11-26 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=30, verbose_name='Xona nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('fee', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vaqt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=190, null=True)),
                ('payt', models.CharField(choices=[('du/chor/ju', 'du/chor/ju'), ('se/pay/shanba', 'se/pay/shanba')], default='du/chor/ju', max_length=25)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guruhlar', to='group.room', verbose_name='xona')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guruhlar', to='group.subject', verbose_name='Fan')),
            ],
        ),
    ]
