# Generated by Django 4.2.7 on 2023-11-26 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guruhlar', to='user.teacher', verbose_name='Ustoz'),
        ),
        migrations.AddField(
            model_name='group',
            name='vaqt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guruhlar', to='group.vaqt', verbose_name='vaqt'),
        ),
    ]
