# Generated by Django 4.2.7 on 2023-11-26 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xabardorlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Royhat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Familiya')),
                ('phone_number_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Asosiy Tel raqam')),
                ('phone_number_2', models.CharField(blank=True, max_length=20, null=True, verbose_name="Qo'shimcha Tel raqam")),
                ('payt', models.CharField(choices=[('du/chor/ju', 'du/chor/ju'), ('se/pay/shanba', 'se/pay/shanba')], default='du/chor/ju', max_length=25)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='group.subject')),
                ('vaqt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='group.vaqt', verbose_name='vaqt')),
                ('xabardor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='register.xabardorlik')),
            ],
        ),
    ]
